require:
  - rubocop-rake
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
# Enforces 1234565789 as 123_456_789 however this feels completely
# inappropriate when dealing with barcodes.
Style/NumericLiterals:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - shared_examples
    - shared_examples_for
    - context
