AllCops:
  TargetRubyVersion: 2.2
# Enforces 1234565789 as 123_456_789 however this feels completely
# inappropriate when dealing with barcodes.
Style/NumericLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - shared_examples
    - shared_examples_for
    - context
